//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SciChart.Xamarin.Views.Core.Common;
using SciChart.Xamarin.Views.Drawing;
using SciChart.Xamarin.Views.Model;
using SciChart.Xamarin.Views.Model.DataSeries;
using SciChart.Xamarin.Views.Visuals.Axes;
using System;
using Xamarin.Forms;


namespace SciChart.Xamarin.Views
{
	
}
namespace SciChart.Xamarin.Views.Visuals.RenderableSeries
{
	
	
	public partial class FastCandlestickRenderableSeries : OhlcRenderableSeriesBase, SciChart.Xamarin.Views.Visuals.RenderableSeries.IFastCandlestickRenderableSeries
	{
		
		public static BindableProperty FillDownBrushStyleProperty = BindableProperty.Create("FillDownBrushStyle", typeof(IBrushStyle), typeof(FastCandlestickRenderableSeries), null, BindingMode.Default, null, OnFillDownBrushStylePropertyChanged, null, null, DefaultFillDownBrushStylePropertyValueCreator);
		
		public static BindableProperty FillUpBrushStyleProperty = BindableProperty.Create("FillUpBrushStyle", typeof(IBrushStyle), typeof(FastCandlestickRenderableSeries), null, BindingMode.Default, null, OnFillUpBrushStylePropertyChanged, null, null, DefaultFillUpBrushStylePropertyValueCreator);
		
		public FastCandlestickRenderableSeries() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewFastCandlestickRenderableSeries())
		{
		}
		
		public IBrushStyle FillDownBrushStyle
		{
			get
			{
				return ((IBrushStyle)(this.GetValue(FillDownBrushStyleProperty)));
			}
			set
			{
				this.SetValue(FillDownBrushStyleProperty, value);
			}
		}
		
		public IBrushStyle FillUpBrushStyle
		{
			get
			{
				return ((IBrushStyle)(this.GetValue(FillUpBrushStyleProperty)));
			}
			set
			{
				this.SetValue(FillUpBrushStyleProperty, value);
			}
		}
		
		private static void OnFillDownBrushStylePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IFastCandlestickRenderableSeries>().FillDownBrushStyle = ((IBrushStyle)(newValue));
		}
		
		private static object DefaultFillDownBrushStylePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IFastCandlestickRenderableSeries>().FillDownBrushStyle;
		}
		
		private static void OnFillUpBrushStylePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IFastCandlestickRenderableSeries>().FillUpBrushStyle = ((IBrushStyle)(newValue));
		}
		
		private static object DefaultFillUpBrushStylePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IFastCandlestickRenderableSeries>().FillUpBrushStyle;
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.RenderableSeries
{
	
	
	public partial class FastLineRenderableSeries : CrossPlatformRenderableSeriesBase, SciChart.Xamarin.Views.Visuals.RenderableSeries.IFastLineRenderableSeries
	{
		
		public FastLineRenderableSeries() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewFastLineRenderableSeries())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.RenderableSeries
{
	
	
	public abstract partial class OhlcRenderableSeriesBase : CrossPlatformRenderableSeriesBase, SciChart.Xamarin.Views.Visuals.RenderableSeries.IOhlcRenderableSeriesBase
	{
		
		public static BindableProperty StrokeDownStyleProperty = BindableProperty.Create("StrokeDownStyle", typeof(IPenStyle), typeof(OhlcRenderableSeriesBase), null, BindingMode.Default, null, OnStrokeDownStylePropertyChanged, null, null, DefaultStrokeDownStylePropertyValueCreator);
		
		public static BindableProperty StrokeUpStyleProperty = BindableProperty.Create("StrokeUpStyle", typeof(IPenStyle), typeof(OhlcRenderableSeriesBase), null, BindingMode.Default, null, OnStrokeUpStylePropertyChanged, null, null, DefaultStrokeUpStylePropertyValueCreator);
		
		public static BindableProperty DataPointWidthProperty = BindableProperty.Create("DataPointWidth", typeof(Double), typeof(OhlcRenderableSeriesBase), null, BindingMode.Default, null, OnDataPointWidthPropertyChanged, null, null, DefaultDataPointWidthPropertyValueCreator);
		
		public IPenStyle StrokeDownStyle
		{
			get
			{
				return ((IPenStyle)(this.GetValue(StrokeDownStyleProperty)));
			}
			set
			{
				this.SetValue(StrokeDownStyleProperty, value);
			}
		}
		
		public IPenStyle StrokeUpStyle
		{
			get
			{
				return ((IPenStyle)(this.GetValue(StrokeUpStyleProperty)));
			}
			set
			{
				this.SetValue(StrokeUpStyleProperty, value);
			}
		}
		
		public Double DataPointWidth
		{
			get
			{
				return ((Double)(this.GetValue(DataPointWidthProperty)));
			}
			set
			{
				this.SetValue(DataPointWidthProperty, value);
			}
		}
		
		private static void OnStrokeDownStylePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IOhlcRenderableSeriesBase>().StrokeDownStyle = ((IPenStyle)(newValue));
		}
		
		private static object DefaultStrokeDownStylePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IOhlcRenderableSeriesBase>().StrokeDownStyle;
		}
		
		private static void OnStrokeUpStylePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IOhlcRenderableSeriesBase>().StrokeUpStyle = ((IPenStyle)(newValue));
		}
		
		private static object DefaultStrokeUpStylePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IOhlcRenderableSeriesBase>().StrokeUpStyle;
		}
		
		private static void OnDataPointWidthPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IOhlcRenderableSeriesBase>().DataPointWidth = ((Double)(newValue));
		}
		
		private static object DefaultDataPointWidthPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IOhlcRenderableSeriesBase>().DataPointWidth;
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.RenderableSeries
{
	
	
	public abstract partial class CrossPlatformRenderableSeriesBase : View, SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries
	{
		
		public static BindableProperty DataSeriesProperty = BindableProperty.Create("DataSeries", typeof(IDataSeries), typeof(CrossPlatformRenderableSeriesBase), null, BindingMode.Default, null, OnDataSeriesPropertyChanged, null, null, DefaultDataSeriesPropertyValueCreator);
		
		public static BindableProperty YAxisIdProperty = BindableProperty.Create("YAxisId", typeof(String), typeof(CrossPlatformRenderableSeriesBase), null, BindingMode.Default, null, OnYAxisIdPropertyChanged, null, null, DefaultYAxisIdPropertyValueCreator);
		
		public static BindableProperty XAxisIdProperty = BindableProperty.Create("XAxisId", typeof(String), typeof(CrossPlatformRenderableSeriesBase), null, BindingMode.Default, null, OnXAxisIdPropertyChanged, null, null, DefaultXAxisIdPropertyValueCreator);
		
		public static BindableProperty StrokeStyleProperty = BindableProperty.Create("StrokeStyle", typeof(IPenStyle), typeof(CrossPlatformRenderableSeriesBase), null, BindingMode.Default, null, OnStrokeStylePropertyChanged, null, null, DefaultStrokeStylePropertyValueCreator);
		
		private SciChart.Xamarin.Views.Core.Common.INativeSciChartObject _nativeSciChartObject;
		
		public IDataSeries DataSeries
		{
			get
			{
				return ((IDataSeries)(this.GetValue(DataSeriesProperty)));
			}
			set
			{
				this.SetValue(DataSeriesProperty, value);
			}
		}
		
		public String YAxisId
		{
			get
			{
				return ((String)(this.GetValue(YAxisIdProperty)));
			}
			set
			{
				this.SetValue(YAxisIdProperty, value);
			}
		}
		
		public String XAxisId
		{
			get
			{
				return ((String)(this.GetValue(XAxisIdProperty)));
			}
			set
			{
				this.SetValue(XAxisIdProperty, value);
			}
		}
		
		public IPenStyle StrokeStyle
		{
			get
			{
				return ((IPenStyle)(this.GetValue(StrokeStyleProperty)));
			}
			set
			{
				this.SetValue(StrokeStyleProperty, value);
			}
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return _nativeSciChartObject;
			}
		}
		
		private static void OnDataSeriesPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries>().DataSeries = ((IDataSeries)(newValue));
		}
		
		private static object DefaultDataSeriesPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries>().DataSeries;
		}
		
		private static void OnYAxisIdPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries>().YAxisId = ((String)(newValue));
		}
		
		private static object DefaultYAxisIdPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries>().YAxisId;
		}
		
		private static void OnXAxisIdPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries>().XAxisId = ((String)(newValue));
		}
		
		private static object DefaultXAxisIdPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries>().XAxisId;
		}
		
		private static void OnStrokeStylePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries>().StrokeStyle = ((IPenStyle)(newValue));
		}
		
		private static object DefaultStrokeStylePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.RenderableSeries.IRenderableSeries>().StrokeStyle;
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.Axes
{
	
	
	public abstract partial class AxisBase : AxisCore, SciChart.Xamarin.Views.Visuals.Axes.IAxis
	{
		
		public static BindableProperty AxisAlignmentProperty = BindableProperty.Create("AxisAlignment", typeof(AxisAlignment), typeof(AxisBase), null, BindingMode.Default, null, OnAxisAlignmentPropertyChanged, null, null, DefaultAxisAlignmentPropertyValueCreator);
		
		public AxisAlignment AxisAlignment
		{
			get
			{
				return ((AxisAlignment)(this.GetValue(AxisAlignmentProperty)));
			}
			set
			{
				this.SetValue(AxisAlignmentProperty, value);
			}
		}
		
		private static void OnAxisAlignmentPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxis>().AxisAlignment = ((AxisAlignment)(newValue));
		}
		
		private static object DefaultAxisAlignmentPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxis>().AxisAlignment;
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.Axes
{
	
	
	public abstract partial class AxisCore : View, SciChart.Xamarin.Views.Visuals.Axes.IAxisCore
	{
		
		public static BindableProperty AxisTitleProperty = BindableProperty.Create("AxisTitle", typeof(String), typeof(AxisCore), null, BindingMode.Default, null, OnAxisTitlePropertyChanged, null, null, DefaultAxisTitlePropertyValueCreator);
		
		public static BindableProperty FlipCoordinatesProperty = BindableProperty.Create("FlipCoordinates", typeof(Boolean), typeof(AxisCore), null, BindingMode.Default, null, OnFlipCoordinatesPropertyChanged, null, null, DefaultFlipCoordinatesPropertyValueCreator);
		
		public static BindableProperty TextFormattingProperty = BindableProperty.Create("TextFormatting", typeof(String), typeof(AxisCore), null, BindingMode.Default, null, OnTextFormattingPropertyChanged, null, null, DefaultTextFormattingPropertyValueCreator);
		
		public static BindableProperty DrawMinorTicksProperty = BindableProperty.Create("DrawMinorTicks", typeof(Boolean), typeof(AxisCore), null, BindingMode.Default, null, OnDrawMinorTicksPropertyChanged, null, null, DefaultDrawMinorTicksPropertyValueCreator);
		
		public static BindableProperty DrawLabelsProperty = BindableProperty.Create("DrawLabels", typeof(Boolean), typeof(AxisCore), null, BindingMode.Default, null, OnDrawLabelsPropertyChanged, null, null, DefaultDrawLabelsPropertyValueCreator);
		
		public static BindableProperty DrawMajorTicksProperty = BindableProperty.Create("DrawMajorTicks", typeof(Boolean), typeof(AxisCore), null, BindingMode.Default, null, OnDrawMajorTicksPropertyChanged, null, null, DefaultDrawMajorTicksPropertyValueCreator);
		
		public static BindableProperty DrawMajorGridLinesProperty = BindableProperty.Create("DrawMajorGridLines", typeof(Boolean), typeof(AxisCore), null, BindingMode.Default, null, OnDrawMajorGridLinesPropertyChanged, null, null, DefaultDrawMajorGridLinesPropertyValueCreator);
		
		public static BindableProperty DrawMinorGridLinesProperty = BindableProperty.Create("DrawMinorGridLines", typeof(Boolean), typeof(AxisCore), null, BindingMode.Default, null, OnDrawMinorGridLinesPropertyChanged, null, null, DefaultDrawMinorGridLinesPropertyValueCreator);
		
		public static BindableProperty DrawMajorBandsProperty = BindableProperty.Create("DrawMajorBands", typeof(Boolean), typeof(AxisCore), null, BindingMode.Default, null, OnDrawMajorBandsPropertyChanged, null, null, DefaultDrawMajorBandsPropertyValueCreator);
		
		public static BindableProperty AxisBandsFillProperty = BindableProperty.Create("AxisBandsFill", typeof(IBrushStyle), typeof(AxisCore), null, BindingMode.Default, null, OnAxisBandsFillPropertyChanged, null, null, DefaultAxisBandsFillPropertyValueCreator);
		
		public static BindableProperty AutoRangeProperty = BindableProperty.Create("AutoRange", typeof(AutoRange), typeof(AxisCore), null, BindingMode.Default, null, OnAutoRangePropertyChanged, null, null, DefaultAutoRangePropertyValueCreator);
		
		public static BindableProperty AxisIdProperty = BindableProperty.Create("AxisId", typeof(String), typeof(AxisCore), null, BindingMode.Default, null, OnAxisIdPropertyChanged, null, null, DefaultAxisIdPropertyValueCreator);
		
		public static BindableProperty VisibleRangeProperty = BindableProperty.Create("VisibleRange", typeof(IRange), typeof(AxisCore), null, BindingMode.Default, null, OnVisibleRangePropertyChanged, null, null, DefaultVisibleRangePropertyValueCreator);
		
		public static BindableProperty GrowByProperty = BindableProperty.Create("GrowBy", typeof(IRange), typeof(AxisCore), null, BindingMode.Default, null, OnGrowByPropertyChanged, null, null, DefaultGrowByPropertyValueCreator);
		
		public static BindableProperty VisibleRangeLimitModeProperty = BindableProperty.Create("VisibleRangeLimitMode", typeof(RangeClipMode), typeof(AxisCore), null, BindingMode.Default, null, OnVisibleRangeLimitModePropertyChanged, null, null, DefaultVisibleRangeLimitModePropertyValueCreator);
		
		public static BindableProperty MinimalZoomConstrainProperty = BindableProperty.Create("MinimalZoomConstrain", typeof(IComparable), typeof(AxisCore), null, BindingMode.Default, null, OnMinimalZoomConstrainPropertyChanged, null, null, DefaultMinimalZoomConstrainPropertyValueCreator);
		
		public static BindableProperty MaximumZoomConstrainProperty = BindableProperty.Create("MaximumZoomConstrain", typeof(IComparable), typeof(AxisCore), null, BindingMode.Default, null, OnMaximumZoomConstrainPropertyChanged, null, null, DefaultMaximumZoomConstrainPropertyValueCreator);
		
		public static BindableProperty MajorDeltaProperty = BindableProperty.Create("MajorDelta", typeof(IComparable), typeof(AxisCore), null, BindingMode.Default, null, OnMajorDeltaPropertyChanged, null, null, DefaultMajorDeltaPropertyValueCreator);
		
		public static BindableProperty MinorDeltaProperty = BindableProperty.Create("MinorDelta", typeof(IComparable), typeof(AxisCore), null, BindingMode.Default, null, OnMinorDeltaPropertyChanged, null, null, DefaultMinorDeltaPropertyValueCreator);
		
		public static BindableProperty AutoTicksProperty = BindableProperty.Create("AutoTicks", typeof(Boolean), typeof(AxisCore), null, BindingMode.Default, null, OnAutoTicksPropertyChanged, null, null, DefaultAutoTicksPropertyValueCreator);
		
		public static BindableProperty MaxAutoTicksProperty = BindableProperty.Create("MaxAutoTicks", typeof(UInt32), typeof(AxisCore), null, BindingMode.Default, null, OnMaxAutoTicksPropertyChanged, null, null, DefaultMaxAutoTicksPropertyValueCreator);
		
		public static BindableProperty MinorsPerMajorProperty = BindableProperty.Create("MinorsPerMajor", typeof(UInt32), typeof(AxisCore), null, BindingMode.Default, null, OnMinorsPerMajorPropertyChanged, null, null, DefaultMinorsPerMajorPropertyValueCreator);
		
		private SciChart.Xamarin.Views.Core.Common.INativeSciChartObject _nativeSciChartObject;
		
		public String AxisTitle
		{
			get
			{
				return ((String)(this.GetValue(AxisTitleProperty)));
			}
			set
			{
				this.SetValue(AxisTitleProperty, value);
			}
		}
		
		public Boolean FlipCoordinates
		{
			get
			{
				return ((Boolean)(this.GetValue(FlipCoordinatesProperty)));
			}
			set
			{
				this.SetValue(FlipCoordinatesProperty, value);
			}
		}
		
		public String TextFormatting
		{
			get
			{
				return ((String)(this.GetValue(TextFormattingProperty)));
			}
			set
			{
				this.SetValue(TextFormattingProperty, value);
			}
		}
		
		public Boolean DrawMinorTicks
		{
			get
			{
				return ((Boolean)(this.GetValue(DrawMinorTicksProperty)));
			}
			set
			{
				this.SetValue(DrawMinorTicksProperty, value);
			}
		}
		
		public Boolean DrawLabels
		{
			get
			{
				return ((Boolean)(this.GetValue(DrawLabelsProperty)));
			}
			set
			{
				this.SetValue(DrawLabelsProperty, value);
			}
		}
		
		public Boolean DrawMajorTicks
		{
			get
			{
				return ((Boolean)(this.GetValue(DrawMajorTicksProperty)));
			}
			set
			{
				this.SetValue(DrawMajorTicksProperty, value);
			}
		}
		
		public Boolean DrawMajorGridLines
		{
			get
			{
				return ((Boolean)(this.GetValue(DrawMajorGridLinesProperty)));
			}
			set
			{
				this.SetValue(DrawMajorGridLinesProperty, value);
			}
		}
		
		public Boolean DrawMinorGridLines
		{
			get
			{
				return ((Boolean)(this.GetValue(DrawMinorGridLinesProperty)));
			}
			set
			{
				this.SetValue(DrawMinorGridLinesProperty, value);
			}
		}
		
		public Boolean DrawMajorBands
		{
			get
			{
				return ((Boolean)(this.GetValue(DrawMajorBandsProperty)));
			}
			set
			{
				this.SetValue(DrawMajorBandsProperty, value);
			}
		}
		
		public IBrushStyle AxisBandsFill
		{
			get
			{
				return ((IBrushStyle)(this.GetValue(AxisBandsFillProperty)));
			}
			set
			{
				this.SetValue(AxisBandsFillProperty, value);
			}
		}
		
		public AutoRange AutoRange
		{
			get
			{
				return ((AutoRange)(this.GetValue(AutoRangeProperty)));
			}
			set
			{
				this.SetValue(AutoRangeProperty, value);
			}
		}
		
		public String AxisId
		{
			get
			{
				return ((String)(this.GetValue(AxisIdProperty)));
			}
			set
			{
				this.SetValue(AxisIdProperty, value);
			}
		}
		
		public IRange VisibleRange
		{
			get
			{
				return ((IRange)(this.GetValue(VisibleRangeProperty)));
			}
			set
			{
				this.SetValue(VisibleRangeProperty, value);
			}
		}
		
		public IRange GrowBy
		{
			get
			{
				return ((IRange)(this.GetValue(GrowByProperty)));
			}
			set
			{
				this.SetValue(GrowByProperty, value);
			}
		}
		
		public RangeClipMode VisibleRangeLimitMode
		{
			get
			{
				return ((RangeClipMode)(this.GetValue(VisibleRangeLimitModeProperty)));
			}
			set
			{
				this.SetValue(VisibleRangeLimitModeProperty, value);
			}
		}
		
		public IComparable MinimalZoomConstrain
		{
			get
			{
				return ((IComparable)(this.GetValue(MinimalZoomConstrainProperty)));
			}
			set
			{
				this.SetValue(MinimalZoomConstrainProperty, value);
			}
		}
		
		public IComparable MaximumZoomConstrain
		{
			get
			{
				return ((IComparable)(this.GetValue(MaximumZoomConstrainProperty)));
			}
			set
			{
				this.SetValue(MaximumZoomConstrainProperty, value);
			}
		}
		
		public IComparable MajorDelta
		{
			get
			{
				return ((IComparable)(this.GetValue(MajorDeltaProperty)));
			}
			set
			{
				this.SetValue(MajorDeltaProperty, value);
			}
		}
		
		public IComparable MinorDelta
		{
			get
			{
				return ((IComparable)(this.GetValue(MinorDeltaProperty)));
			}
			set
			{
				this.SetValue(MinorDeltaProperty, value);
			}
		}
		
		public Boolean AutoTicks
		{
			get
			{
				return ((Boolean)(this.GetValue(AutoTicksProperty)));
			}
			set
			{
				this.SetValue(AutoTicksProperty, value);
			}
		}
		
		public UInt32 MaxAutoTicks
		{
			get
			{
				return ((UInt32)(this.GetValue(MaxAutoTicksProperty)));
			}
			set
			{
				this.SetValue(MaxAutoTicksProperty, value);
			}
		}
		
		public UInt32 MinorsPerMajor
		{
			get
			{
				return ((UInt32)(this.GetValue(MinorsPerMajorProperty)));
			}
			set
			{
				this.SetValue(MinorsPerMajorProperty, value);
			}
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return _nativeSciChartObject;
			}
		}
		
		private static void OnAxisTitlePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AxisTitle = ((String)(newValue));
		}
		
		private static object DefaultAxisTitlePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AxisTitle;
		}
		
		private static void OnFlipCoordinatesPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().FlipCoordinates = ((Boolean)(newValue));
		}
		
		private static object DefaultFlipCoordinatesPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().FlipCoordinates;
		}
		
		private static void OnTextFormattingPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().TextFormatting = ((String)(newValue));
		}
		
		private static object DefaultTextFormattingPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().TextFormatting;
		}
		
		private static void OnDrawMinorTicksPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMinorTicks = ((Boolean)(newValue));
		}
		
		private static object DefaultDrawMinorTicksPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMinorTicks;
		}
		
		private static void OnDrawLabelsPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawLabels = ((Boolean)(newValue));
		}
		
		private static object DefaultDrawLabelsPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawLabels;
		}
		
		private static void OnDrawMajorTicksPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMajorTicks = ((Boolean)(newValue));
		}
		
		private static object DefaultDrawMajorTicksPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMajorTicks;
		}
		
		private static void OnDrawMajorGridLinesPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMajorGridLines = ((Boolean)(newValue));
		}
		
		private static object DefaultDrawMajorGridLinesPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMajorGridLines;
		}
		
		private static void OnDrawMinorGridLinesPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMinorGridLines = ((Boolean)(newValue));
		}
		
		private static object DefaultDrawMinorGridLinesPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMinorGridLines;
		}
		
		private static void OnDrawMajorBandsPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMajorBands = ((Boolean)(newValue));
		}
		
		private static object DefaultDrawMajorBandsPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().DrawMajorBands;
		}
		
		private static void OnAxisBandsFillPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AxisBandsFill = ((IBrushStyle)(newValue));
		}
		
		private static object DefaultAxisBandsFillPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AxisBandsFill;
		}
		
		private static void OnAutoRangePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AutoRange = ((AutoRange)(newValue));
		}
		
		private static object DefaultAutoRangePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AutoRange;
		}
		
		private static void OnAxisIdPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AxisId = ((String)(newValue));
		}
		
		private static object DefaultAxisIdPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AxisId;
		}
		
		private static void OnVisibleRangePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().VisibleRange = ((IRange)(newValue));
		}
		
		private static object DefaultVisibleRangePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().VisibleRange;
		}
		
		private static void OnGrowByPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().GrowBy = ((IRange)(newValue));
		}
		
		private static object DefaultGrowByPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().GrowBy;
		}
		
		private static void OnVisibleRangeLimitModePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().VisibleRangeLimitMode = ((RangeClipMode)(newValue));
		}
		
		private static object DefaultVisibleRangeLimitModePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().VisibleRangeLimitMode;
		}
		
		private static void OnMinimalZoomConstrainPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MinimalZoomConstrain = ((IComparable)(newValue));
		}
		
		private static object DefaultMinimalZoomConstrainPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MinimalZoomConstrain;
		}
		
		private static void OnMaximumZoomConstrainPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MaximumZoomConstrain = ((IComparable)(newValue));
		}
		
		private static object DefaultMaximumZoomConstrainPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MaximumZoomConstrain;
		}
		
		private static void OnMajorDeltaPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MajorDelta = ((IComparable)(newValue));
		}
		
		private static object DefaultMajorDeltaPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MajorDelta;
		}
		
		private static void OnMinorDeltaPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MinorDelta = ((IComparable)(newValue));
		}
		
		private static object DefaultMinorDeltaPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MinorDelta;
		}
		
		private static void OnAutoTicksPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AutoTicks = ((Boolean)(newValue));
		}
		
		private static object DefaultAutoTicksPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().AutoTicks;
		}
		
		private static void OnMaxAutoTicksPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MaxAutoTicks = ((UInt32)(newValue));
		}
		
		private static object DefaultMaxAutoTicksPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MaxAutoTicks;
		}
		
		private static void OnMinorsPerMajorPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MinorsPerMajor = ((UInt32)(newValue));
		}
		
		private static object DefaultMinorsPerMajorPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Axes.IAxisCore>().MinorsPerMajor;
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.Axes
{
	
	
	public partial class NumericAxis : AxisBase, SciChart.Xamarin.Views.Visuals.Axes.INumericAxis
	{
		
		public NumericAxis() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewNumericAxis())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.Axes3D
{
	
	
	public abstract partial class AxisBase3D : AxisCore, SciChart.Xamarin.Views.Visuals.Axes3D.IAxis3D
	{
	}
}
namespace SciChart.Xamarin.Views.Visuals.Axes3D
{
	
	
	public partial class NumericAxis3D : AxisBase3D, SciChart.Xamarin.Views.Visuals.Axes3D.INumericAxis3D
	{
		
		public NumericAxis3D() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewNumericAxis3D())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.Annotations
{
	
	
	public abstract partial class AnnotationBase : View, SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation
	{
		
		public static BindableProperty X1Property = BindableProperty.Create("X1", typeof(IComparable), typeof(AnnotationBase), null, BindingMode.Default, null, OnX1PropertyChanged, null, null, DefaultX1PropertyValueCreator);
		
		public static BindableProperty X2Property = BindableProperty.Create("X2", typeof(IComparable), typeof(AnnotationBase), null, BindingMode.Default, null, OnX2PropertyChanged, null, null, DefaultX2PropertyValueCreator);
		
		public static BindableProperty Y1Property = BindableProperty.Create("Y1", typeof(IComparable), typeof(AnnotationBase), null, BindingMode.Default, null, OnY1PropertyChanged, null, null, DefaultY1PropertyValueCreator);
		
		public static BindableProperty Y2Property = BindableProperty.Create("Y2", typeof(IComparable), typeof(AnnotationBase), null, BindingMode.Default, null, OnY2PropertyChanged, null, null, DefaultY2PropertyValueCreator);
		
		public static BindableProperty XAxisIdProperty = BindableProperty.Create("XAxisId", typeof(String), typeof(AnnotationBase), null, BindingMode.Default, null, OnXAxisIdPropertyChanged, null, null, DefaultXAxisIdPropertyValueCreator);
		
		public static BindableProperty YAxisIdProperty = BindableProperty.Create("YAxisId", typeof(String), typeof(AnnotationBase), null, BindingMode.Default, null, OnYAxisIdPropertyChanged, null, null, DefaultYAxisIdPropertyValueCreator);
		
		public static BindableProperty IsEditableProperty = BindableProperty.Create("IsEditable", typeof(Boolean), typeof(AnnotationBase), null, BindingMode.Default, null, OnIsEditablePropertyChanged, null, null, DefaultIsEditablePropertyValueCreator);
		
		public static BindableProperty IsHiddenProperty = BindableProperty.Create("IsHidden", typeof(Boolean), typeof(AnnotationBase), null, BindingMode.Default, null, OnIsHiddenPropertyChanged, null, null, DefaultIsHiddenPropertyValueCreator);
		
		public static BindableProperty DragDirectionsProperty = BindableProperty.Create("DragDirections", typeof(Direction2D), typeof(AnnotationBase), null, BindingMode.Default, null, OnDragDirectionsPropertyChanged, null, null, DefaultDragDirectionsPropertyValueCreator);
		
		public static BindableProperty ResizeDirectionsProperty = BindableProperty.Create("ResizeDirections", typeof(Direction2D), typeof(AnnotationBase), null, BindingMode.Default, null, OnResizeDirectionsPropertyChanged, null, null, DefaultResizeDirectionsPropertyValueCreator);
		
		private SciChart.Xamarin.Views.Core.Common.INativeSciChartObject _nativeSciChartObject;
		
		public IComparable X1
		{
			get
			{
				return ((IComparable)(this.GetValue(X1Property)));
			}
			set
			{
				this.SetValue(X1Property, value);
			}
		}
		
		public IComparable X2
		{
			get
			{
				return ((IComparable)(this.GetValue(X2Property)));
			}
			set
			{
				this.SetValue(X2Property, value);
			}
		}
		
		public IComparable Y1
		{
			get
			{
				return ((IComparable)(this.GetValue(Y1Property)));
			}
			set
			{
				this.SetValue(Y1Property, value);
			}
		}
		
		public IComparable Y2
		{
			get
			{
				return ((IComparable)(this.GetValue(Y2Property)));
			}
			set
			{
				this.SetValue(Y2Property, value);
			}
		}
		
		public String XAxisId
		{
			get
			{
				return ((String)(this.GetValue(XAxisIdProperty)));
			}
			set
			{
				this.SetValue(XAxisIdProperty, value);
			}
		}
		
		public String YAxisId
		{
			get
			{
				return ((String)(this.GetValue(YAxisIdProperty)));
			}
			set
			{
				this.SetValue(YAxisIdProperty, value);
			}
		}
		
		public Boolean IsEditable
		{
			get
			{
				return ((Boolean)(this.GetValue(IsEditableProperty)));
			}
			set
			{
				this.SetValue(IsEditableProperty, value);
			}
		}
		
		public Boolean IsHidden
		{
			get
			{
				return ((Boolean)(this.GetValue(IsHiddenProperty)));
			}
			set
			{
				this.SetValue(IsHiddenProperty, value);
			}
		}
		
		public Direction2D DragDirections
		{
			get
			{
				return ((Direction2D)(this.GetValue(DragDirectionsProperty)));
			}
			set
			{
				this.SetValue(DragDirectionsProperty, value);
			}
		}
		
		public Direction2D ResizeDirections
		{
			get
			{
				return ((Direction2D)(this.GetValue(ResizeDirectionsProperty)));
			}
			set
			{
				this.SetValue(ResizeDirectionsProperty, value);
			}
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return _nativeSciChartObject;
			}
		}
		
		private static void OnX1PropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().X1 = ((IComparable)(newValue));
		}
		
		private static object DefaultX1PropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().X1;
		}
		
		private static void OnX2PropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().X2 = ((IComparable)(newValue));
		}
		
		private static object DefaultX2PropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().X2;
		}
		
		private static void OnY1PropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().Y1 = ((IComparable)(newValue));
		}
		
		private static object DefaultY1PropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().Y1;
		}
		
		private static void OnY2PropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().Y2 = ((IComparable)(newValue));
		}
		
		private static object DefaultY2PropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().Y2;
		}
		
		private static void OnXAxisIdPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().XAxisId = ((String)(newValue));
		}
		
		private static object DefaultXAxisIdPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().XAxisId;
		}
		
		private static void OnYAxisIdPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().YAxisId = ((String)(newValue));
		}
		
		private static object DefaultYAxisIdPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().YAxisId;
		}
		
		private static void OnIsEditablePropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().IsEditable = ((Boolean)(newValue));
		}
		
		private static object DefaultIsEditablePropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().IsEditable;
		}
		
		private static void OnIsHiddenPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().IsHidden = ((Boolean)(newValue));
		}
		
		private static object DefaultIsHiddenPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().IsHidden;
		}
		
		private static void OnDragDirectionsPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().DragDirections = ((Direction2D)(newValue));
		}
		
		private static object DefaultDragDirectionsPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().DragDirections;
		}
		
		private static void OnResizeDirectionsPropertyChanged(BindableObject bindable, object oldValue, object newValue)
		{
			bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().ResizeDirections = ((Direction2D)(newValue));
		}
		
		private static object DefaultResizeDirectionsPropertyValueCreator(BindableObject bindable)
		{
			return bindable.CastBindableWrapper<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().ResizeDirections;
		}
		
		public void Show()
		{
			NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().Show();
		}
		
		public void Hide()
		{
			NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().Hide();
		}
		
		public void MoveBasePointTo(float xCoord, float yCoord, int index)
		{
			NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().MoveBasePointTo(xCoord, yCoord, index);
		}
		
		public void MoveAnnotation(float horizontalOffset, float verticalOffset)
		{
			NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Visuals.Annotations.IAnnotation>().MoveAnnotation(horizontalOffset, verticalOffset);
		}
	}
}
namespace SciChart.Xamarin.Views.Visuals.Annotations
{
	
	
	public partial class BoxAnnotation : AnnotationBase, SciChart.Xamarin.Views.Visuals.Annotations.IBoxAnnotation
	{
		
		public BoxAnnotation() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewBoxAnnotation())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Modifiers
{
	
	
	public abstract partial class ChartModifierBase : ChartModifierCore, SciChart.Xamarin.Views.Modifiers.IChartModifier
	{
	}
}
namespace SciChart.Xamarin.Views.Modifiers
{
	
	
	public abstract partial class ChartModifierCore : View, SciChart.Xamarin.Views.Modifiers.IChartModifierCore
	{
		
		private SciChart.Xamarin.Views.Core.Common.INativeSciChartObject _nativeSciChartObject;
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return _nativeSciChartObject;
			}
		}
	}
}
namespace SciChart.Xamarin.Views.Modifiers
{
	
	
	public partial class ModifierGroup : ChartModifierBase, SciChart.Xamarin.Views.Modifiers.IModifierGroup
	{
		
		public ModifierGroup() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewModifierGroup())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Modifiers
{
	
	
	public partial class PinchZoomModifier : ChartModifierBase, SciChart.Xamarin.Views.Modifiers.IPinchZoomModifier
	{
		
		public PinchZoomModifier() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewPinchZoomModifier())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Modifiers
{
	
	
	public partial class TooltipModifier : ChartModifierBase, SciChart.Xamarin.Views.Modifiers.ITooltipModifier
	{
		
		public TooltipModifier() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewTooltipModifier())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Modifiers
{
	
	
	public partial class ZoomExtentsModifier : ChartModifierBase, SciChart.Xamarin.Views.Modifiers.IZoomExtentsModifier
	{
		
		public ZoomExtentsModifier() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewZoomExtentsModifier())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Modifiers
{
	
	
	public partial class ZoomPanModifier : ChartModifierBase, SciChart.Xamarin.Views.Modifiers.IZoomPanModifier
	{
		
		public ZoomPanModifier() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewZoomPanModifier())
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Model
{
	
	
	public partial class DoubleRange : RangeBase, SciChart.Xamarin.Views.Model.IDoubleRange
	{
		
		public DoubleRange() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewDoubleRange())
		{
		}
		
		public DoubleRange(double min, double max) : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewDoubleRange(min, max))
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Model.DataSeries
{
	
	
	public abstract partial class CrossPlatformDataSeriesBase : SciChart.Xamarin.Views.Model.DataSeries.IDataSeries
	{
		
		private SciChart.Xamarin.Views.Core.Common.INativeSciChartObject _nativeSciChartObject;
		
		public String SeriesName
		{
			get
			{
				return NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Model.DataSeries.IDataSeries>().SeriesName;
			}
			set
			{
				NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Model.DataSeries.IDataSeries>().SeriesName = value;
			}
		}
		
		public Int32 Count
		{
			get
			{
				return NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Model.DataSeries.IDataSeries>().Count;
			}
		}
		
		public Boolean AcceptsUnsortedData
		{
			get
			{
				return NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Model.DataSeries.IDataSeries>().AcceptsUnsortedData;
			}
			set
			{
				NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Model.DataSeries.IDataSeries>().AcceptsUnsortedData = value;
			}
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return _nativeSciChartObject;
			}
		}
	}
}
namespace SciChart.Xamarin.Views.Model.DataSeries
{
	
	
	public partial class OhlcDataSeries<TX, TY> : CrossPlatformDataSeriesBase, SciChart.Xamarin.Views.Model.DataSeries.IOhlcDataSeries<TX,TY>
		where TX : System.IComparable
		where TY : System.IComparable
	{
		
		public OhlcDataSeries() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewOhlcDataSeries<TX, TY>())
		{
		}
		
		public void Append(TX x, TY open, TY high, TY low, TY close)
		{
			NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Model.DataSeries.IOhlcDataSeries<TX,TY>>().Append(x, open, high, low, close);
		}
	}
}
namespace SciChart.Xamarin.Views.Model.DataSeries
{
	
	
	public partial class XyDataSeries<TX, TY> : CrossPlatformDataSeriesBase, SciChart.Xamarin.Views.Model.DataSeries.IXyDataSeries<TX,TY>
		where TX : System.IComparable
		where TY : System.IComparable
	{
		
		public XyDataSeries() : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewXyDataSeries<TX, TY>())
		{
		}
		
		public void Append(TX x, TY y)
		{
			NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Model.DataSeries.IXyDataSeries<TX,TY>>().Append(x, y);
		}
		
		public void Append(System.Collections.Generic.IEnumerable<TX> xValues, System.Collections.Generic.IEnumerable<TY> yValues)
		{
			NativeSciChartObject.CastSciChartObject<SciChart.Xamarin.Views.Model.DataSeries.IXyDataSeries<TX,TY>>().Append(xValues, yValues);
		}
	}
}
namespace SciChart.Xamarin.Views.Drawing
{
	
	
	public abstract partial class BrushStyle : SciChart.Xamarin.Views.Drawing.IBrushStyle
	{
		
		private SciChart.Xamarin.Views.Core.Common.INativeSciChartObject _nativeSciChartObject;
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return _nativeSciChartObject;
			}
		}
	}
}
namespace SciChart.Xamarin.Views.Drawing
{
	
	
	public partial class FontStyle : SciChart.Xamarin.Views.Drawing.IFontStyle
	{
		
		private SciChart.Xamarin.Views.Core.Common.INativeSciChartObject _nativeSciChartObject;
		
		public FontStyle(float textSize, System.Drawing.Color textColor) : 
				this(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewFontStyle(textSize, textColor))
		{
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return _nativeSciChartObject;
			}
		}
	}
}
namespace SciChart.Xamarin.Views.Drawing
{
	
	
	public partial class LinearGradientBrushStyle : BrushStyle, SciChart.Xamarin.Views.Drawing.ILinearGradientBrushStyle
	{
		
		public LinearGradientBrushStyle(float x1, float y1, float x2, float y2, System.Drawing.Color startColor, System.Drawing.Color endColor) : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewLinearGradientBrushStyle(x1, y1, x2, y2, startColor, endColor))
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Drawing
{
	
	
	public abstract partial class PenStyle : SciChart.Xamarin.Views.Drawing.IPenStyle
	{
		
		private SciChart.Xamarin.Views.Core.Common.INativeSciChartObject _nativeSciChartObject;
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return _nativeSciChartObject;
			}
		}
	}
}
namespace SciChart.Xamarin.Views.Drawing
{
	
	
	public partial class SolidBrushStyle : BrushStyle, SciChart.Xamarin.Views.Drawing.ISolidBrushStyle
	{
		
		public SolidBrushStyle(System.Drawing.Color color) : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewSolidBrushStyle(color))
		{
		}
	}
}
namespace SciChart.Xamarin.Views.Drawing
{
	
	
	public partial class SolidPenStyle : PenStyle, SciChart.Xamarin.Views.Drawing.ISolidPenStyle
	{
		
		public SolidPenStyle(System.Drawing.Color color, float thickness, bool antiAliasing, float[] strokeDashArray) : 
				base(DependencyService.Get<SciChart.Xamarin.Views.Core.Common.INativeSciChartObjectFactory>().NewSolidPenStyle(color, thickness, antiAliasing, strokeDashArray))
		{
		}
	}
}
