//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Xamarin.Forms;


namespace SciChart.Xamarin.iOS.Renderer
{
	using SciChart.iOS.Charting;
	using SciChart.Xamarin.iOS.Renderer.Utility;
	
	
	public partial class FastLineRenderableSeriesiOS : SCIFastLineRenderableSeries, SciChart.Xamarin.Views.Visuals.RenderableSeries.IFastLineRenderableSeries, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public FastLineRenderableSeriesiOS()
		{
		}
		
		public SciChart.Xamarin.Views.Model.DataSeries.IDataSeries DataSeries
		{
			get
			{
				return base.DataSeries.DataSeriesToXamarin();
			}
			set
			{
				base.DataSeries = value.DataSeriesFromXamarin();
			}
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class NumericAxisiOS : SCINumericAxis, SciChart.Xamarin.Views.Visuals.Axes.INumericAxis, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public NumericAxisiOS()
		{
		}
		
		public SciChart.Xamarin.Views.Visuals.Axes.AxisAlignment AxisAlignment
		{
			get
			{
				return base.AxisAlignment.AlignmentToXamarin();
			}
			set
			{
				base.AxisAlignment = value.AlignmentFromXamarin();
			}
		}
		
		public Color AxisBandsFill
		{
			get
			{
				return base.AxisBandsStyle.BrushStyleToXamarin();
			}
			set
			{
				base.AxisBandsStyle = value.BrushStyleFromXamarin();
			}
		}
		
		public SciChart.Xamarin.Views.Visuals.Axes.AutoRange AutoRange
		{
			get
			{
				return base.AutoRange.AutoRangeToXamarin();
			}
			set
			{
				base.AutoRange = value.AutoRangeFromXamarin();
			}
		}
		
		public SciChart.Xamarin.Views.Model.IRange VisibleRange
		{
			get
			{
				return base.VisibleRange.RangeToXamarin();
			}
			set
			{
				base.VisibleRange = value.RangeFromXamarin();
			}
		}
		
		public SciChart.Xamarin.Views.Model.IRange GrowBy
		{
			get
			{
				return base.GrowBy.RangeToXamarin();
			}
			set
			{
				base.GrowBy = value.RangeFromXamarin();
			}
		}
		
		public SciChart.Xamarin.Views.Model.RangeClipMode VisibleRangeLimitMode
		{
			get
			{
				return base.VisibleRangeLimitMode.RangeClipModeToXamarin();
			}
			set
			{
				base.VisibleRangeLimitMode = value.RangeClipModeFromXamarin();
			}
		}
		
		public System.IComparable MinimalZoomConstrain
		{
			get
			{
				return base.MinimalZoomConstrain.ComparableToXamarin();
			}
			set
			{
				base.MinimalZoomConstrain = value.ComparableFromXamarin();
			}
		}
		
		public System.IComparable MaximumZoomConstrain
		{
			get
			{
				return base.MaximumZoomConstrain.ComparableToXamarin();
			}
			set
			{
				base.MaximumZoomConstrain = value.ComparableFromXamarin();
			}
		}
		
		public System.IComparable MajorDelta
		{
			get
			{
				return base.MajorDelta.ComparableToXamarin();
			}
			set
			{
				base.MajorDelta = value.ComparableFromXamarin();
			}
		}
		
		public System.IComparable MinorDelta
		{
			get
			{
				return base.MinorDelta.ComparableToXamarin();
			}
			set
			{
				base.MinorDelta = value.ComparableFromXamarin();
			}
		}
		
		public uint MaxAutoTicks
		{
			get
			{
				return base.MaxAutoTicks.UIntToXamarin();
			}
			set
			{
				base.MaxAutoTicks = value.UIntFromXamarin();
			}
		}
		
		public uint MinorsPerMajor
		{
			get
			{
				return base.MinorsPerMajor.UIntToXamarin();
			}
			set
			{
				base.MinorsPerMajor = value.UIntFromXamarin();
			}
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class BoxAnnotationiOS : SCIBoxAnnotation, SciChart.Xamarin.Views.Visuals.Annotations.IBoxAnnotation, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public BoxAnnotationiOS()
		{
		}
		
		public System.IComparable X1
		{
			get
			{
				return base.X1Value;
			}
			set
			{
				base.X1Value = value;
			}
		}
		
		public System.IComparable X2
		{
			get
			{
				return base.X2Value;
			}
			set
			{
				base.X2Value = value;
			}
		}
		
		public System.IComparable Y1
		{
			get
			{
				return base.Y1Value;
			}
			set
			{
				base.Y1Value = value;
			}
		}
		
		public System.IComparable Y2
		{
			get
			{
				return base.Y2Value;
			}
			set
			{
				base.Y2Value = value;
			}
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class ModifierGroupiOS : SCIModifierGroup, SciChart.Xamarin.Views.Modifiers.IModifierGroup, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public ModifierGroupiOS()
		{
		}
		
		public ModifierGroupiOS(SciChart.iOS.Charting.IISCIChartModifier[] childModifiers) : 
				base(childModifiers)
		{
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class PinchZoomModifieriOS : SCIPinchZoomModifier, SciChart.Xamarin.Views.Modifiers.IPinchZoomModifier, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public PinchZoomModifieriOS()
		{
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class TooltipModifieriOS : SCITooltipModifier, SciChart.Xamarin.Views.Modifiers.ITooltipModifier, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public TooltipModifieriOS()
		{
		}
		
		public TooltipModifieriOS(SciChart.iOS.Charting.SCICrossDrawableBehavior crossDrawableBehavior) : 
				base(crossDrawableBehavior)
		{
		}
		
		public TooltipModifieriOS(SciChart.iOS.Charting.SCICrossDrawableBehavior crossDrawableBehavior, SciChart.iOS.Charting.IISCITooltipContainer tooltipContainer) : 
				base(crossDrawableBehavior, tooltipContainer)
		{
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class ZoomExtentsModifieriOS : SCIZoomExtentsModifier, SciChart.Xamarin.Views.Modifiers.IZoomExtentsModifier, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public ZoomExtentsModifieriOS()
		{
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class ZoomPanModifieriOS : SCIZoomPanModifier, SciChart.Xamarin.Views.Modifiers.IZoomPanModifier, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public ZoomPanModifieriOS()
		{
		}
		
		public ZoomPanModifieriOS(System.nuint defaultNumberOfTouches) : 
				base(defaultNumberOfTouches)
		{
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class DoubleRangeiOS : SCIDoubleRange, SciChart.Xamarin.Views.Model.IDoubleRange, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
	{
		
		public DoubleRangeiOS()
		{
		}
		
		public DoubleRangeiOS(double min, double max) : 
				base(min, max)
		{
		}
		
		public DoubleRangeiOS(SciChart.iOS.Charting.SCIDoubleRange range) : 
				base(range)
		{
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class XyDataSeriesiOS<TX, TY> : XyDataSeries<TX,TY>, SciChart.Xamarin.Views.Model.DataSeries.IXyDataSeries<TX,TY>, SciChart.Xamarin.Views.Core.Common.INativeSciChartObject
		where TX : System.IComparable
		where TY : System.IComparable
	{
		
		public XyDataSeriesiOS()
		{
		}
		
		public SciChart.Xamarin.Views.Core.Common.INativeSciChartObject NativeSciChartObject
		{
			get
			{
				return this;
			}
		}
	}
	
	public partial class iOSFactory
	{
		
		public SciChart.Xamarin.Views.Visuals.RenderableSeries.IFastLineRenderableSeries NewFastLineRenderableSeries()
		{
			return new FastLineRenderableSeriesiOS();
		}
		
		public SciChart.Xamarin.Views.Visuals.Axes.INumericAxis NewNumericAxis()
		{
			return new NumericAxisiOS();
		}
		
		public SciChart.Xamarin.Views.Model.DataSeries.IXyDataSeries<TX,TY> NewXyDataSeries<TX, TY>()
			where TX : System.IComparable
			where TY : System.IComparable
		{
			return new XyDataSeriesiOS<TX,TY>();
		}
		
		public SciChart.Xamarin.Views.Model.IDoubleRange NewDoubleRange(double min, double max)
		{
			return new DoubleRangeiOS(min, max);
		}
		
		public SciChart.Xamarin.Views.Model.IDoubleRange NewDoubleRange()
		{
			return new DoubleRangeiOS();
		}
		
		public SciChart.Xamarin.Views.Visuals.Annotations.IBoxAnnotation NewBoxAnnotation()
		{
			return new BoxAnnotationiOS();
		}
		
		public SciChart.Xamarin.Views.Modifiers.IZoomPanModifier NewZoomPanModifier()
		{
			return new ZoomPanModifieriOS();
		}
		
		public SciChart.Xamarin.Views.Modifiers.IPinchZoomModifier NewPinchZoomModifier()
		{
			return new PinchZoomModifieriOS();
		}
		
		public SciChart.Xamarin.Views.Modifiers.ITooltipModifier NewTooltipModifier()
		{
			return new TooltipModifieriOS();
		}
		
		public SciChart.Xamarin.Views.Modifiers.IZoomExtentsModifier NewZoomExtentsModifier()
		{
			return new ZoomExtentsModifieriOS();
		}
		
		public SciChart.Xamarin.Views.Modifiers.IModifierGroup NewModifierGroup()
		{
			return new ModifierGroupiOS();
		}
	}
}
